Background.o: Background.cc Background.h Resource.h Preferences.h \
 Database.h Color.h Timer.h
BusyCursor.o: BusyCursor.cc BusyCursor.h Resource.h Preferences.h \
 Database.h Color.h Background.h Timer.h
Button.o: Button.cc Button.h Event.h Resource.h Preferences.h \
 Database.h Color.h Background.h Timer.h Action.h Window.h Canvas.h \
 Text.h
Canvas.o: Canvas.cc Canvas.h Resource.h Preferences.h Database.h \
 Color.h Background.h Timer.h
Color.o: Color.cc Color.h Resource.h Preferences.h Database.h \
 Background.h Timer.h
Database.o: Database.cc Database.h
Desktop.o: Desktop.cc Desktop.h Container.h Resource.h Preferences.h \
 Database.h Color.h Background.h Timer.h Action.h BusyCursor.h \
 Device.h Link.h Image.h Window.h Event.h Label.h Canvas.h Text.h \
 Menu.h Trash.h Dialog.h Button.h
Device.o: Device.cc Timer.h Resource.h Preferences.h Database.h \
 Color.h Background.h Device.h Link.h Container.h Image.h Window.h \
 Event.h Label.h Canvas.h Text.h Menu.h Action.h Dialog.h Button.h
Dialog.o: Dialog.cc Dialog.h Window.h Resource.h Preferences.h \
 Database.h Color.h Background.h Timer.h Event.h Action.h Canvas.h \
 Button.h Text.h Desktop.h Container.h
Editor.o: Editor.cc Editor.h Window.h Resource.h Preferences.h \
 Database.h Color.h Background.h Timer.h Event.h Canvas.h Text.h
Event.o: Event.cc Event.h Resource.h Preferences.h Database.h Color.h \
 Background.h Timer.h Window.h
Image.o: Image.cc Image.h Window.h Resource.h Preferences.h Database.h \
 Color.h Background.h Timer.h Event.h
Label.o: Label.cc Label.h Window.h Resource.h Preferences.h Database.h \
 Color.h Background.h Timer.h Event.h Canvas.h Text.h
Link.o: Link.cc Link.h Database.h Container.h Image.h Window.h \
 Resource.h Preferences.h Color.h Background.h Timer.h Event.h Label.h \
 Canvas.h Text.h Menu.h Action.h BusyCursor.h Dialog.h Button.h \
 LinkEditor.h Editor.h
LinkEditor.o: LinkEditor.cc LinkEditor.h Dialog.h Window.h Resource.h \
 Preferences.h Database.h Color.h Background.h Timer.h Event.h \
 Action.h Canvas.h Button.h Editor.h Link.h Container.h Image.h \
 Label.h Text.h Menu.h
Main.o: Main.cc Desktop.h Container.h Resource.h Preferences.h \
 Database.h Color.h Background.h Timer.h Action.h
Menu.o: Menu.cc Menu.h Event.h Resource.h Preferences.h Database.h \
 Color.h Background.h Timer.h Window.h Canvas.h Action.h Text.h \
 Desktop.h Container.h
Preferences.o: Preferences.cc Preferences.h Database.h
Resource.o: Resource.cc Resource.h Preferences.h Database.h Color.h \
 Background.h Timer.h BusyCursor.h Penguin.h
Text.o: Text.cc Text.h Resource.h Preferences.h Database.h Color.h \
 Background.h Timer.h
Timer.o: Timer.cc Timer.h Resource.h Preferences.h Database.h Color.h \
 Background.h
Trash.o: Trash.cc Trash.h Timer.h Resource.h Preferences.h Database.h \
 Color.h Background.h Link.h Container.h Image.h Window.h Event.h \
 Label.h Canvas.h Text.h Menu.h Action.h
Window.o: Window.cc Window.h Resource.h Preferences.h Database.h \
 Color.h Background.h Timer.h Event.h
