CXX   = g++
VDESK = vdesk
THREAD_LIB = -lpthread
.if exists(Makefile.cfg)
include Makefile.cfg
.if exists(Makefile.dep)
do-it-all: $(VDESK)
include Makefile.dep
.else
do-it-all: dep_build
.endif
.else
do-it-all: config
.endif

include Makefile.common
