CXX   = g++
VDESK = vdesk
ifeq (Makefile.cfg,$(wildcard Makefile.cfg))
include Makefile.cfg
ifeq (Makefile.dep,$(wildcard Makefile.dep))
do-it-all: $(VDESK)
include Makefile.dep
else
do-it-all: dep
endif
else
do-it-all: config
endif

include Makefile.common
